apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green
  namespace: argocd
spec:
  project: default
  sources:
    - chart: app
      repoURL: s3://skills-chart-bucket-sija/app
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - https://raw.githubusercontent.com/24sunrin015/day1-values/main/green.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: skills
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
