apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: {{ .Release.Namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/app/*.log
        Parser            json
        Tag               app.*

    [FILTER]
        Name        grep
        Match       app.*
        # /health 로그 제외
        Regex       path ^((?!/health).)*$

    [OUTPUT]
        Name  es
        Match app.*
        Host  {{ .Values.fluentbit.opensearchHost }}
        Port  {{ .Values.fluentbit.opensearchPort }}
        Index app-log
        Type  _doc
